db:
   image: mongo
web:
   image: parseplatform/parse-server
   links: 
    - db
   ports:
    - "1337:1337"
   command: --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://db/test
parse-dashboard:
  image: parseplatform/parse-dashboard
  ports:
    - 8080:4040
  environment:
    - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=true
  volumes:
    - './DashboradConfig/parse-dashboard-config.json:/src/Parse-Dashboard/parse-dashboard-config.json'

